### ISSUE TITLE
Overlays contain transparent / translucent pixels outside the desired area

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-Saturn#1]
Some overlays contain transparent / translucent pixels outside the desired area.

Here the list:

Astal (USA).png
Marvel Super Heroes vs. Street Fighter (Japan).png
Night Warriors - Darkstalkers' Revenge (USA).png

Here you can see the specific areas that have pixels outside the desired area.

![Astal (USA)](https://user-images.githubusercontent.com/20826760/74788759-f10c6880-52b2-11ea-8c46-9a7fce00547f.png)
![Marvel Super Heroes vs  Street Fighter (Japan)](https://user-images.githubusercontent.com/20826760/74788764-f7024980-52b2-11ea-9d23-0f0261136748.png)
![Night Warriors - Darkstalkers' Revenge (USA)](https://user-images.githubusercontent.com/20826760/74788768-fa95d080-52b2-11ea-84d6-fe6a2f6daa75.png)

**Comment by toniosj** [comment]
I hope not bother. As you have all fixed so fast, I don't know if you have any problems with this system...
Great job and thank you very much.

**Comment by thebezelproject** [comment]
Updated.
